services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass secret
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
